-- command to run script: sqlite3 StoryForge.db < create_storyforge_db.sql

PRAGMA foreign_keys = ON;



-- if tables exist, delete them
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USERINFO;
DROP TABLE IF EXISTS ADVENTURES;



CREATE TABLE USERS (
    USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL
);

-- Create USERINFO Table
CREATE TABLE USERINFO (
    USER_ID INTEGER,
    EMAIL TEXT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Create ADVENTURES Table
CREATE TABLE ADVENTURES (
    ADVENTURE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);